### ISSUE TITLE
"Marver" / "DC" comics characters instead of comic "Karakuri circus" characters

### ISSUE THREAD

**Issue by 3timeslazy** [raohwork/marionette-go#1]
Сan it be better to use the names of world famous superheroes from `MARVEL / DS` instead of `Karakuri circus`?

**Comment by Ronmi** [comment]
Thank for the suggestion.

It's still WIP so I'll keep these names until first stable version. It is much easier for me to understand what kind of works the struct/interface should do.

Later in the first stable version (which would be 3.0.0, matches marionette protocol version), all these struct/interface/package names will be more "straight forward".

If the names are difficult to remember for you, but still need this lib right now, here's a snippet:

```go
import (
	"github.com/raohwork/marionette-go/automata"
	"github.com/raohwork/marionette-go/shirogane"
)

type Client struct {
	shirogane.Ashihana
}

func NewClient(addr string) (ret *Client) {
	return &Client{Ashihana: shirogane.Ashihana{
		Kuroga: &shirogane.Mixed{Addr: addr},
	}}
}

type TabManager struct {
	automata.Columbine
}

func NewTabManager(c *Client, tabs []string) (ret *TabManager, err error) {
	m, err := automata.NewColumbine(&c.Ashihana, tabs)
	if err == nil {
		ret = &TabManager{Columbine: m}
	}
	return
}
```

I'll leave this issue open til I rename the structs.
